spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: true
      uri: http://localhost8081
      allowOverride: ~
      overrideNone: ~
    bootstrap:
      enabled: true

  config:
    import=optional:
      configserver: http://localhost:8081