spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: customer-service
  cloud:
    config:
      enabled: true
      uri: http://localhost8081
      username: root
      password: s3cr3t
      allowOverride: ~
      overrideNone: ~
    bootstrap:
      enabled: true