spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: customer-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
    bootstrap:
      enabled: true